### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by glensc** [bulletmark/cdhist#12]
Trying to figure out what version I am running is difficult:

```
✖  cdhist --version
usage: cdhist [-i] [-h] [-p] [-a] [-g] [-r] [-u] [-l] [-m SIZE] [-L] [-P] [directory]
cdhist: error: unrecognized arguments: --version
```

**Comment by bulletmark** [comment]
I've added this with commit 026b43e because (since Python 3.8) it is not very awkward although I personally disagree with the need for it and have avoided adding it for all my many other Python packages/tools on github.

Is `pip show cdhist` really "difficult"? Also, versions are actually set and better interrogated via your systems package manager. E.g. [`pkglog`](https://github.com/bulletmark/pkglog)`cdhist` shows the current version and the date history of that and previous versions. The system version often augments the native version, e.g. On Arch the current version is `cdhist 3.6-1` which compared to native version `3.6` shows the last build version which can/must change for various external reasons. In short, you should check a programs version via your package manager, not via the program itself.

**Comment by glensc** [comment]
> Is `pip show cdhist` really "difficult"?

yep, it is. you have to know which pip you used to install initially. and it changes over time depending what is current "default" python in brew:
- https://github.com/bulletmark/cdhist/issues/7#issuecomment-1319307558

```
➜ head -n1 `which cdhist`
#!/usr/local/opt/python@3.10/bin/python3.10
```
