### ISSUE TITLE
Feature: print to stdout

### ISSUE THREAD

**Issue by glensc** [bulletmark/cdhist#3]
why is the program printing to the terminal directly? this makes it impossible to filter the output!

```
cd -l | grep -i back
```

tried also stderr (which is common problem):
```
cd -l 2>&1|grep -i back
```

**Comment by bulletmark** [comment]
Look at the `cdhist.rc` file which shows how it works. `cdhist` program writes the target directory to stdout so that can be captured and passed to the real `cd` command. So the only way `cdhist` can write to the user is to write to `/dev/tty`.

There is a *much* better way to do what you want to do though. Read the [section about FZF](https://github.com/bulletmark/cdhist#fzf-integration) integration. Just press ALT+C and start typing "back" and it will fuzzy search and/or you can cursor down to your choice. If you really want to `grep` (e.g. from a script), then just `grep -i back ~/.cd_history`.

**Comment by bulletmark** [comment]
Thinking about this more, the error messages at least can simply be written to stderr, not to `/dev/tty`, so commit 2f6092e (new version 2.8) changes this. I could actually change the remaining `/dev/tty` writes to use a temporary (e.g. ram based) file, or a named pipe, etc but this would degrade performance and I am very conscious of the increased latency in `cd` commands on low resource machines like raspberry pi.

**Comment by glensc** [comment]
you could create extra pipe for communication, or extra pipe for stdout.

```sh

# create fd#3 and connect it with stdout
exec 3>&1

blimp() {
	echo "this goes to fd#3" >&3
	echo "this goes to fd#1" >&1
}

captured=$(blimp)

echo "Captured: $captured"

# close fd#3
exec 3>&-
```

once executed, it shows:

```
➜ sh issue-3.sh
this goes to fd#3
Captured: this goes to fd#1
```

**Comment by bulletmark** [comment]
I don't consider this a practical problem so am closing this issue.

BTW, apart from the 2 better approaches I mention above, there is also `cd -/back` available.
